apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app }}-secrets"
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  DBUSER: "{{ .Values.db.user }}"
  DBPASS: "{{ .Values.db.pass }}"
